export const puzzleTable = `CREATE TABLE IF NOT EXISTS public.puzzles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    owner bigint NOT NULL,
    CONSTRAINT puzzles_pkey PRIMARY KEY (id)
)`;
